### ISSUE TITLE
Problem with access the centroid of ground truth map

### ISSUE THREAD

**Issue by IvanFei** [DengPingFan/S-measure#1]
Hi, @DengPingFan 

Thank you for sharing the code.

I have a question for you about get the centroid of ground truth.

Assume ground truth  `a` is:
`
a = [[0, 0, 0, 0]; [0, 1, 1, 0];
[0, 1, 1, 0]; [0, 0, 0, 0]]
`
Assume prediction saliency map `b` is:
`
b = [[0, 0, 0, 0]; [0, 0.9, 0.9, 0];
[0, 0.9, 0.9, 0]; [0, 0.1, 0.1, 0]]
`

your code get the centroid `X=3, Y=3`, and you get the blocks with 
`
block1 = [[0, 0, 0]; [0, 1, 1]; [0, 1, 1]; [0, 0, 0]]  
`
`
block2 = [[0]; [0]; [0]]
`
`
block3 = ...
`
It may incorrect. 

If there is any problem with my understanding, please contact me.

Thank you very much.

sincerely.

**Comment by DengPingFan** [comment]
Hi, 
   Note that when the image size is even, the center of the GT may be shift a little. 
For this case, GT will be divided into four block, that is 
GT_block1 = [[0, 0, 0]; [0, 1, 1]; [0, 1, 1]; [0, 0, 0]] 
GT_block2 = [[0]; [0]; [0]]
GT_block3 = [[0,0,0]]
GT_block4 = [[0]]


For predicted map, it will be normalized (d_prediction = reshape(mapminmax(d_prediction(:)',0,1),size(d_prediction))) as
predicted [[0, 0, 0, 0]; [0, 1, 1, 0]; [0, 1, 1, 0]; [0, 0.111, 0.111, 0]]


also, it will be seperated as: 
pre_block1 = [[0, 0, 0]; [0, 1, 1]; [0, 1, 1]; [0, 0, 0]]
pre_block2 = [[0]; [0.111]; [0.111]]
pre_block3 = [[0,0,0]]
pre_block4 = [[0]]



After computing by S_region, the score will be 0.8981. 
I don't quite understand what is your question? Why incorrect?


------------------ 原始邮件 ------------------
发件人: "fei"<notifications@github.com>;
发送时间: 2019年9月11日(星期三) 晚上7:51
收件人: "DengPingFan/S-measure"<S-measure@noreply.github.com>;
抄送: "Deng-Ping Fan"<381620505@qq.com>;"Mention"<mention@noreply.github.com>;
主题: [DengPingFan/S-measure] Problem with access the centroid of groundtruth map (#1)




Hi, @DengPingFan
 
Thank you for sharing the code.
 
I have a question for you about get the centroid of ground truth.
 
Assume ground truth  a is:
 a = [[0, 0, 0, 0]; [0, 1, 1, 0]; [0, 1, 1, 0]; [0, 0, 0, 0]]
 Assume prediction saliency map b is:
 b = [[0, 0, 0, 0]; [0, 0.9, 0.9, 0]; [0, 0.9, 0.9, 0]; [0, 0.1, 0.1, 0]]
 
your code get the centroid X=3, Y=3, and you get the blocks with
 block1 = [[0, 0, 0]; [0, 1, 1]; [0, 1, 1]; [0, 0, 0]]  
 block2 = [[0]; [0]; [0]]
 block3 = ...
 It may incorrect.
 
If there is any problem with my understanding, please contact me.
 
Thank you very much.
 
sincerely.

**Comment by IvanFei** [comment]
> Hi, Note that when the image size is even, the center of the GT may be shift a little. For this case, GT will be divided into four block, that is GT_block1 = [[0, 0, 0]; [0, 1, 1]; [0, 1, 1]; [0, 0, 0]] GT_block2 = [[0]; [0]; [0]] GT_block3 = [[0,0,0]] GT_block4 = [[0]] For predicted map, it will be normalized (d_prediction = reshape(mapminmax(d_prediction(:)',0,1),size(d_prediction))) as predicted [[0, 0, 0, 0]; [0, 1, 1, 0]; [0, 1, 1, 0]; [0, 0.111, 0.111, 0]] also, it will be seperated as: pre_block1 = [[0, 0, 0]; [0, 1, 1]; [0, 1, 1]; [0, 0, 0]] pre_block2 = [[0]; [0.111]; [0.111]] pre_block3 = [[0,0,0]] pre_block4 = [[0]] After computing by S_region, the score will be 0.8981. I don't quite understand what is your question? Why incorrect?
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: "fei"<notifications@github.com>; 发送时间: 2019年9月11日(星期三) 晚上7:51 收件人: "DengPingFan/S-measure"<S-measure@noreply.github.com>; 抄送: "Deng-Ping Fan"<381620505@qq.com>;"Mention"<mention@noreply.github.com>; 主题: [DengPingFan/S-measure] Problem with access the centroid of groundtruth map (#1) Hi, @DengPingFan Thank you for sharing the code. I have a question for you about get the centroid of ground truth. Assume ground truth a is: a = [[0, 0, 0, 0]; [0, 1, 1, 0]; [0, 1, 1, 0]; [0, 0, 0, 0]] Assume prediction saliency map b is: b = [[0, 0, 0, 0]; [0, 0.9, 0.9, 0]; [0, 0.9, 0.9, 0]; [0, 0.1, 0.1, 0]] your code get the centroid X=3, Y=3, and you get the blocks with block1 = [[0, 0, 0]; [0, 1, 1]; [0, 1, 1]; [0, 0, 0]] block2 = [[0]; [0]; [0]] block3 = ... It may incorrect. If there is any problem with my understanding, please contact me. Thank you very much. sincerely. — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub, or mute the thread.

Aha, Thank you for your kind reply.
In my opinion, the correct answer of above case is:
GT_block1 = [[0, 0]; [0, 1]]
GT_block2 = [[0, 0]; [1, 0]]
GT_block3 = [[0, 1]; [0, 0]]
GT_block4 = [[1, 0]; [0, 0]]
The center coordinate value should be `floor(X)` and `floor(Y)`
The shift may be ignore when test in the images, because the the error is tiny.
